Document: hpower
Title: Debian hpower Manual
Author: <insert document author here>
Abstract: This manual describes what hpower is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hpower/hpower.sgml.gz

Format: postscript
Files: /usr/share/doc/hpower/hpower.ps.gz

Format: text
Files: /usr/share/doc/hpower/hpower.text.gz

Format: HTML
Index: /usr/share/doc/hpower/html/index.html
Files: /usr/share/doc/hpower/html/*.html

  
